version: 0.2
env:
  variables:
    PROJECT: github.com/iph
phases:
  install:
    commands:
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - cd /tmp && curl -o terraform.zip https://releases.hashicorp.com/terraform/0.14.3/terraform_0.14.3_linux_amd64.zip && unzip terraform.zip && mv terraform /usr/bin
      - cd $CODEBUILD_SRC_DIR/
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/pipelines/full_aws
      - sh configuration.sh example
      - terraform apply -auto-approve
